### PR TITLE
Update Patterns.podspec

### PR DESCRIPTION
**Pull request by SagarSDagdu**

### CODE REVIEW

**Comment by SagarSDagdu** [comment]
After merging this PR, please run
`pod repo push Patterns Patterns.podspec` to push this to cocoapods. Please let me know if you face any issues in this step.

**Review by vinayjn — APPROVED** [review]

**Comment by vinayjn** [comment]
Thank you, merging this.

**Comment by SagarSDagdu** [comment]
Hi @vinayjn , were you able to push the podspec to cocoapods repo...?

**Comment by vinayjn** [comment]
I did, can you try installing `pod patterns-swift`

**Comment by SagarSDagdu** [comment]
@vinayjn , I tried but it didn't work. Can you send me the link for this on cocoapods.org? Like for example, this is the link for one of my libs : https://cocoapods.org/pods/SDDownloadManager

**Comment by SagarSDagdu** [comment]
Alternatively, you can add me as a collaborator to this repo, and I can fix this issue.
Currently, this is the issue that is stopping me from creating a pod entry : 

Screen Shot 2020-05-10 at 1 47 13 PM

**Pull request merged**
